title: Niels Nyholt
url: "https://nnyholt.github.io"
baseurl: 

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "CV"
   link: "cv"
 - name: "Contact"
   link: "contact"
